# 389. Find the Difference
# Solved
# Easy
# Topics
# Companies
# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.



def findTheDifference(s,t):
            # Initialize a dictionary to count the occurrences of characters in string t
        char_count = {}
        # Count the occurrences of each character in string t
        for char in t:
            char_count[char] = char_count.get(char, 0) + 1
        
        # Subtract the count of characters in string s from the count of characters in string t
        for char in s:
            char_count[char] -= 1
        
        # Find the character with a count greater than 0 in the remaining characters of t,
        # which is the added character in t
        for char, count in char_count.items():
            if count > 0:
                return char
            
print(findTheDifference("abcd","abcde"))